name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]  # windows-2019

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.7.4

      - name: Setup VS environment (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-*"
          CIBW_BEFORE_ALL: "python -m pip install invoke && invoke build.all"
          CIBW_TEST_REQUIRES: "pytest mypy flake8 black"
          CIBW_TEST_COMMAND: "python -m invoke test"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
