name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]  # windows-2019

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.7.4

      - name: Build dependencies
        run: |
          python -m pip install invoke requests pytest twine
          invoke build.all

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-*"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
