name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.7.4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-*"
          # The C libraries (OpenSSL and Zlib) only need to be built once per OS
          # as they are not tied to a specific Python version
          CIBW_BEFORE_ALL: "python -m pip install invoke && invoke build.deps"
          # However the nassl C extension is by design tied to a specific Python version
          CIBW_BEFORE_BUILD: "python -m pip install invoke && invoke build.nassl"
          CIBW_BEFORE_BUILD_WINDOWS: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "python -m pytest {project}/tests"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
